// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5qKsPnhzxDBDuCtRgxwNfllfi2RBeu8M',
    appId: '1:695073298717:web:ba30503af5590be15029f4',
    messagingSenderId: '695073298717',
    projectId: 'authexample1-80228',
    authDomain: 'authexample1-80228.firebaseapp.com',
    storageBucket: 'authexample1-80228.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEq0p5KjTvtHP81Jiz26nvGrQimlk9juk',
    appId: '1:695073298717:android:2020259fef6dea245029f4',
    messagingSenderId: '695073298717',
    projectId: 'authexample1-80228',
    storageBucket: 'authexample1-80228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVTvQXUW4GNP6ahKXzKPex303O8OmND10',
    appId: '1:695073298717:ios:61042707f20821365029f4',
    messagingSenderId: '695073298717',
    projectId: 'authexample1-80228',
    storageBucket: 'authexample1-80228.firebasestorage.app',
    iosClientId: '695073298717-n17j0vhfe4pv2f240sio158v5h9oapef.apps.googleusercontent.com',
    iosBundleId: 'com.example.authExample1',
  );
}
